# Initialize a new or existing Terraform working directory
- name: Terraform Init
  run: terraform -chdir=./your-subdirectory init

# Format Terraform files
- name: Terraform Format
  run: terraform -chdir=./your-subdirectory fmt -check

# Generate an execution plan
- name: Terraform Plan
  run: terraform -chdir=./your-subdirectory plan -input=false

# Apply the changes (on push to master)
- name: Terraform Apply
  if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  run: terraform -chdir=./your-subdirectory apply -auto-approve -input=false
